### PR TITLE
Load plugin via requirejs

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Load plugin via requirejs which triggers init function.

## Motivation
With rollup, we can utilise its power to minimize the size of the final bundle.

## Screenshot
image

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
FYI: a web component can easily be loaded via requirejs - see https://github.com/owncloud/phoenix/pull/2584/files#diff-7d271f2c0c292de60eb38753c3f74438R39

Here is how a web component is built using vue cli3: https://github.com/DeepDiver1975/phoenix-demo-web-component

Looking at this ^ I question if we need any additional mechanism for the time being.

@felixboehm we basically should finish our discussion about stable and explicit extension points vs a (maybe too) generic mechanism.

**Comment by DeepDiver1975** [comment]
Can you also please write down the reasons for using rollup? 

Looks like you are building a umd lib and load this via requirejs.
First of all an AMD compatible module should be enough for requirejs.
Second also WebPack can generate an AMD or UMD.

The choosen tool should be not relevant .....

THX

aboud AMD and UMD: https://www.davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/

**Comment by LukasHirt** [comment]
> Can you also please write down the reasons for using rollup?

Experimenting with different approaches. With rollup, we seem to easily overcome the issue with pretty big bundles after building the extensions.

Also, a bit of inspiration from here https://medium.com/@kazu_pon/vue-cli-plugin-p11n-a51195ff7d3e where rollup is being used as well.

**Comment by DeepDiver1975** [comment]
> Experimenting with different approaches. With rollup, we seem to easily overcome the issue with pretty big bundles after building the extensions.
> 
> Also, a bit of inspiration from here https://medium.com/@kazu_pon/vue-cli-plugin-p11n-a51195ff7d3e where rollup is being used as well.

So it was just the first to be successful - this does not mean that it is a hard requirement to use rollup in any case. Right?

One can implement a UMD with plain js as well - no tools required ;-)

**Comment by LukasHirt** [comment]
> this does not mean that it is a hard requirement to use rollup in any case. Right?

Yes. It is not. This is more about a search on how to optimise the solution we had with webpack. And since there were some code-splitting issues, rollup seemed like a nice alternative.

**Comment by LukasHirt** [comment]
I am going to merge this as we went with rollup in multiple extensions already so we can point to this as a reference.

**Pull request merged**
